services:
    database:
        image: 'mysql:8.0.31'
        container_name: nyt-database
        restart: unless-stopped
        ports:
            - '${DB_PORT:-3306}:${DB_PORT:-3306}'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - volume-nyt-database:/var/lib/mysql
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
        networks:
            - nyt

    php:
        build:
            context: .
            dockerfile: ./docker/php.dockerfile
            target: php-fpm
            args:
                UID: '${UID}'
                GID: '${GID}'
        environment:
            - 'PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}'
        container_name: nyt-php
        user: '${UID}:${GID}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./source:/var/www/html:cached
        networks:
            - nyt
        depends_on:
            - database

    nginx-fpm:
        image: 'nginx:stable-alpine'
        container_name: nyt-nginx-fpm
        restart: unless-stopped
        ports:
            - '${NGINX_PORT:-80}:80'
        volumes:
            - ./source:/var/www/html:cached
            - ./docker/confs/nginx.conf:/etc/nginx.conf
            - ./docker/confs/sites:/etc/nginx/conf.d
        networks:
            - nyt
        depends_on:
            - php
            - database

    redis:
        image: redis
        container_name: nyt-redis
        volumes:
            - volume-nyt-redis:/data
        ports:
            - "${REDIS_PORT-6379}:${REDIS_PORT-6379}"
        networks:
            - nyt


volumes:
    volume-nyt-database:
        driver: local
    volume-nyt-redis:
        driver: local

networks:
  nyt:
    driver: bridge
