name: Check Code Quality

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
        working-directory: source

      - name: Run Laravel Pint (check only)
        run: ./vendor/bin/pint --test
        working-directory: source

      - name: Run Laravel Pint (fix)
        if: failure()
        run: |
          ./vendor/bin/pint
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Apply Laravel Pint formatting fixes"
          git push
        working-directory: source
        continue-on-error: true

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
        working-directory: source

      - name: Run PHP Insights
        run: ./vendor/bin/phpinsights analyse --config-path=config/insights.php
        working-directory: source

      - name: Setup Test Environment
        run: |
          cp .env.example .env
          php artisan key:generate --env=testing
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/views
          mkdir -p storage/framework/sessions
          chmod -R 775 storage
        working-directory: source

      - name: Run Pest Tests
        run: ./vendor/bin/pest
        working-directory: source
